// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutMenu: typeof import('@nutui/nutui-taro')['Menu']
    NutMenuItem: typeof import('@nutui/nutui-taro')['MenuItem']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutPrice: typeof import('@nutui/nutui-taro')['Price']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
  }
}
